sudo: required
dist: trusty

language: java
jdk:
- oraclejdk8

cache:
  directories:
  - $HOME/.m2/repository

before_install:
  # allocate commits to CI, not the owner of the deploy key
  - git config user.name "opentracingci"
  - git config user.email "opentracingci+opentracing@googlegroups.com"

  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials

install:
  # Override default travis to use the maven wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - ./travis/publish.sh

branches:
  except:
    - /^[0-9]/

env:
  global:
  # Ex. travis encrypt -r org/repo GH_TOKEN=XXX-https://github.com/settings/tokens-XXX
  - secure: "YkN8wc0ZNSKn7covjYlSoGOLBDrYATDLXoAChxeqtzGTuoP7U2W0YqCgs6m1XuV9UHqZR6+VxS+SaQwyYO4yafXYoSFiiNbfGo+aNGSiXVQYmrhZo+iRjHl/LTWfx9ctDwF6J/YdrO6HhnCnl1cqRmKV4DJ3agbQbAIwXK36eCkYmCwCOWbqNsD9zRs+1uUUWiaXt3X7wBJ/y3xoAeg2NqtpN0QXQ8VEGk7S6GOuwjDVaaxODyKRGm0KmzPcoUbCnn1Bmf036EM31gVSYx2Boi1YcvAAyK+rhbDrnl490U8GGDMJJkBX+f907BUu1b0LWKNcfaaGdn35aXETiDhdIVo2tmro4T8wj3raPWI52DWwPMK71XKcxvHCcldF39Rj1dEiw4vLoOGlQ5mnOkUV9hgF77RTzxavFO8TCW0ENzXsVAfgOXaPN0rSLcdZy4nY+L70JSA2yMpNpYwlunqknYL1Grzco9VxCyH457igpxleKk2DOL9rNJ1pkOg45EDx7eF2WMnuav/PmwJx386cdDNiV/uUyeZ3NsSWllyk11loAJL8fHtatT9qnyjD9CSglx8lOitr4udeG7nJV+g7o9UQCBg9aWKJENWX7WGtyPlpCnmWKiMaodMyMD5nGhVqJ4rqbUD2KP2WYvgK97CSfdDhlgg8/hYmsxymp0WzSP0="
  # Ex. travis encrypt -r org/repo SONATYPE_USER=your_sonatype_account
  - secure: "HqDBeouG6bwCraA//G1SkicBO8sEa9wlWbfH1sA6CZP2wIJWFp9FMIW65X/hgzZ8uB+Kjb3jPjhBh2IylsfR9MY19Myz6N/cLIPhP2goGCBh5JyofBiX0hLiNPu20XPDomRqgp14FrEg+8tQSNXHvHsQ2lAq+gi9XiIyrwqFQlN8qY3Br9iAym+1umYmiYfiZ+u4ogTQie4haQfizSL9fmBx6TnWhJjVGlMT7fdnfA99lM1eamMXQcA58b6SxjS7zvFIwZm2AJWIbY9Y2mrqCUzazE4Bmzs/uGNA/pw9tCMA9lpPfkEYwEGKvPbqnV0Ze4WKC0zHfS8akb0Ke3t9/WNSHEJ7Q+YCjtzs1J24+WjTsH3LHibT2yGqPRjuADnTX/Zf5WRcl2iMseMZpK6ps9LlwzIecTSLiWTHkwl6xQQbzaT4AUby7OR7F23i2jtsD+A1jhAF7oQ73GokmpIYGyzu6iFz7MxbDYFPZZq3Y+l0AvM8i0x15EVNm6a8HQsp327O5RqUdJgD1QB2yYBcz5geZsc3ErW26RIi2mGEqDo3pG3kRfd/Vprzs7xRkiwEq1lgrRbzSfMwBzFCFH1l7D/NBN8j/7JV9e+3lAhMBvVzfXQHONEcTLz8+2Ms1xdg1PDDFWtnl/aixBoyUaLUkE/Y3OBNV2/al4vhK34TsrI="
  # Ex. travis encrypt -r org/repo SONATYPE_PASSWORD=your_sonatype_password
  - secure: "F59XVjS2ywe/tV+CVIpu0b6OGZ44eFIh7JHUIS3dwVMGqVeo1q8vP0xElugj2rDAmPX3xw2TgxWs8ZSzA7MTyG13fPobVbmFS3xuzwLyHjv+U5YVbXo4vp1h3iC6kgeMrxpCyDmkjrs2/CJfUcwTCVZ0g00/TLh35chXGHXwJg7KGAMnf6nAYZH4+5jg27tPZVUTKb8KvyUmjQbiYH9YqNK8FRkS1oz0p2522JOkypm5lMb10Z+ZSTwFXzK0IeKZop+RdexCaxoMH+Kr26jCP6qBG77RB1koQSHKWzClvph3ijhrUNnT10pm37RBZHyZDSm2vyuaeRb3/EI9MKyESwaSv0o23p19CBZT2ufgLVrTj54cHJSUrDnApwJj5oTnNC4xweaTF5TGmUToLMT9Iokb3ij5SAUKIirBVm/wIh4wMLuqiSdG58h4AqRIg4N4cgjDJey7bJ13kL0MANppPSUm4h53TNX5E/B0c2RRnWXT/Y8av9gEl2Edq7Nt1Ue2SRzw2a6sv30tizJRtuDGnHGiMDG6/Z3/yofIXihGqMyw8bO4OVWIgIR6rGK6y1hsc9CpIFjWs6F3fJEl1xgQCUOqkQvtHFRAodMb6f+E4DWmwJTD+O344eJgLk8WzArwexZOnz7HANxyzoql3hXFbZLCg3hlH/nk53Z0vogVTCE="
  # Ex. travis encrypt -r org/repo BINTRAY_USER=your_github_account
  - secure: "Ot5CTIrrd44d1eOvNe36rwM2KGO4PXkWE4tEMxuGzLAiqE1UCxMp0hDLm7HlQvV6dQoM5mjLcWAZRjxH1ne9sPytxYAzWR1XnghssLVf79fDKzW+qKWYNCDwPhECVxikQvHRB+ZKEL0KsvPVYC5llc5Lcqah4OijEA9We49XgZfQeHoN28xawlNkVjV39/iS8p5eVa9V5Zq1lmQ34QaZdxl7BPQmRtJ+8TzqKQCE3tkKVrVNgS3l61Hw4wy2JFVwcjfWmKiKImZQweDsmBeAu1Z19jpDBIacTL4+RimpOJT+xieheKVF4RvCSQ6nL4mwDnHZYWMBhRysaAlb5EPHvyJmi1rrYfRa4DfEg9ZcDllxiG9BjpZ/n/LvWmVjJhibuBsQTH3ZYFuM8HKRc3r+/8lvj37iRF/rrRtQBNcY8hfaFxCILkAx6HVBbyaD/8sHxMmXvn0QNNmR3R4WCs9RSlAjPgAsbRDhHm10loK6xxJBSPLI0VVux4QJD/CyDPe9rJZrcB+UUf4hoknzmd3XybtFfJqc7TZlMq7Ic6RBAJb8MnokLiCgxuDqpx7ilzCG1ERd13PQHluzaWQ0Yq4A+l0d0BLmuCCXh6JYFk9EIWCfhxXwtQBXJnuu2NtgomxMRNKReBeWWLMf8YqAHM0cEsPABDAkw0sFztg3x47ee5c="
  # Ex. travis encrypt -r org/repo BINTRAY_KEY=xxx-https://bintray.com/profile/edit-xxx
  - secure: "Xv6FbcXiYkkk+w7kklKyCxDxWhlPGw1hApeGRxfoB96oXV2ozKyFdQQCnReC79CrIxFp/B+zG/JI+r/SrIyxwVbkhlT6Ovv0wfA7goOTAEfeR7cYw83u0S1bHlbeHLCTZFBUaTWISGdRroIE6vRHTWcJfCysP1d20VNcw7e2RQlm1gvTdzXVdUEL8saTgQ/gQaPD2NCVlgKPSInKsP/zk/cwtyzxZ0JavU0dYet2fL3d24ukjYh8Vl9A6cVyxpW5ZpxnxgNSpPAnOs8306KK9y8tZpR8V5MwG/eBiTgY/NQtia0aDWfC4y9u3dXAGBMiInhXE7rGlfuyJA6HbS1y/c5x+/fxh0dalVYtUvsmMFQW6mNy9wTrCgo3hvQPcYx4/TVLkanZm04hnD1uTPKujIJxSrwFyL0e49QICzeua3RLywfvFxCbko9tYTVrcMlFVqFYabDdwCL1ZsPBf+DttU3KyPf0lCAQ2bJsa7v6em3rpYnp3Y6CLt96+UtJPIBwmT+sStGeeD2AQdOQoTnQEGRFkQU1v0VANziRE7ESRZzg7z75POQuCJTGtA1XnVnJj4FwR64wFR9K0LGwkBXX8aVnLHJm0lA5ogrJwRX+0n11bb1GdkKsHymf9l1zPPnSlshGyaediblxnOzG9HGE4S/0hqPcTcNGyTUUceyhAOs="
